export const ROUTES = {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  MAIN: 'MAIN',
  DASHBOARD: 'DASHBOARD',
  ADDEVENT: 'ADDEVENT',
  EVENTLIST: 'EVENTLIST',
  PROFILE: 'PROFILE',
  EVENTLISTSTACKSCREEN: 'EVENTLISTSTACKSCREEN',
  PROFILESTACKSCREEN: 'PROFILESTACKSCREEN',
  SETTING: 'SETTING',
  EVENTDETAILS: 'EVENTDETAILS',
} as const;
type RouteKeys = keyof typeof ROUTES;
